[default]
# Place non-sensitive defaults here; copy to secrets.toml for local runs.
# api_key = "replace-with-your-key"
# db_url = "postgresql://user:pass@host:port/dbname"

[google_service_account]
# Paste the contents of your service account JSON here (values shown are placeholders).
type = "service_account"
project_id = "your-project-id"
private_key_id = "0000000000000000000000000000000000000000"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEv...\n-----END PRIVATE KEY-----\n"
client_email = "service-account@your-project.iam.gserviceaccount.com"
client_id = "000000000000000000000"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-account%40your-project.iam.gserviceaccount.com"

[google_drive]
# Optional: default folder to upload into. Leave blank to use My Drive root.
folder_id = ""

[google_oauth]
# OAuth client for user-based Drive access (Desktop application type).
client_id = "your-client-id.apps.googleusercontent.com"
client_secret = "your-client-secret"
project_id = "your-project-id"
# redirect_uri (or redirect_uris array) must match the OAuth client settings.
# For copy-paste auth codes, leave at the out-of-band default below and ensure the
# OAuth client is created as "Desktop" in Google Cloud Console.
redirect_uri = "urn:ietf:wg:oauth:2.0:oob"
# auth_uri, token_uri などは既定値を使用する場合、削除しても構いません。

[dify]
# APIキーとAPIベースURL (通常は既定値でOK) を設定します。
api_key = "your-dify-api-key"
# base_url = "https://api.dify.ai"
# user = "streamlit-user"
