[default]
# シェアしても良い安全な値をここに設定します。

[gcs]
bucket_name = "your-bucket-name"
# project_id はサービスアカウントの JSON に含まれていれば省略可能です。
project_id = "your-project-id"
# 任意: バケット内のアップロード先プレフィックス。
upload_prefix = "optional/subdir"
# Uniform bucket-level access を利用する場合は false のままにしてください。
make_public = false

[gcs.service_account]
# Google Cloud のサービスアカウント JSON をここにペーストします。
type = "service_account"
project_id = "your-project-id"
private_key_id = "0000000000000000000000000000000000000000"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEv...
-----END PRIVATE KEY-----"""
client_email = "service-account@your-project.iam.gserviceaccount.com"
client_id = "000000000000000000000"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-account%40your-project.iam.gserviceaccount.com"

[dify]
# Dify の API キーなどがあれば設定します。
api_key = "your-dify-api-key"
# base_url = "https://api.dify.ai"
# user = "streamlit-user"
